"""empty message

Revision ID: a8e0bd38d847
Revises: c4d195f1a707
Create Date: 2023-01-13 09:58:18.128910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e0bd38d847'
down_revision = 'c4d195f1a707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('id_index')
        batch_op.drop_index('task_order')
        batch_op.drop_index('task_tasklist')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offline_db', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('offline_db')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('task_tasklist', ['id', 'task_list_id'], unique=False)
        batch_op.create_index('task_order', ['order', 'task_list_id'], unique=False)
        batch_op.create_index('id_index', ['id'], unique=False)

    # ### end Alembic commands ###
