"""empty message

Revision ID: c4d195f1a707
Revises: 0c17a2cf8792
Create Date: 2023-01-06 12:12:17.813589

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c4d195f1a707'
down_revision = '0c17a2cf8792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
